name: Hello Api

on:
  push:
    branches:
      - main

jobs:
  say_hi:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        name: Checking out our code

      - name: Checking that Luis is not cheating
        run: "ls -l"

      - name: Checking that Vlad is doing the right thing
        run:  echo "I'm your nightmare"